version = 1

[[analyzers]]
name = "swift"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor",
    "angularjs"
  ]
  environment = [
    "browser",
    "jquery",
    "mongo",
    "nodejs",
    "jest",
    "cypress",
    "vitest",
    "mocha",
    "jasmine"
  ]

[[analyzers]]
name = "sql"

[[analyzers]]
name = "php"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "scalafmt"